In [1]:
import pandas as pd

In [2]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
genes = ["BRCA1", "TP53", "EGFR", "MYC", "PTEN"]
control_expression = [10.5, 8.2, 5.6, 9.1, 7.4]
treatment_expression = [15.2, 7.9, 12.3, 14.8, 6.9]
significant = ["Yes", "No", "Yes", "Yes", "No"]

In [4]:
rows = list(zip(
    genes,
    control_expression,
    treatment_expression,
    significant
))

In [5]:
df = pd.DataFrame(
    rows,
    columns=["Gene", "Control Expression", "Treatment Expression", "Significant"]
    )
print(df)

    Gene  Control Expression  Treatment Expression Significant
0  BRCA1                10.5                  15.2         Yes
1   TP53                 8.2                   7.9          No
2   EGFR                 5.6                  12.3         Yes
3    MYC                 9.1                  14.8         Yes
4   PTEN                 7.4                   6.9          No

In [6]:
gene_data = {
    "Gene": genes,
    "Control_Expression": control_expression,
    "Treatment_Expression": treatment_expression,
    "Significant": significant
    }

In [7]:
df = pd.DataFrame(gene_data)
df

    Gene  Control_Expression  Treatment_Expression Significant
0  BRCA1                10.5                  15.2         Yes
1   TP53                 8.2                   7.9          No
2   EGFR                 5.6                  12.3         Yes
3    MYC                 9.1                  14.8         Yes
4   PTEN                 7.4                   6.9          No

In [8]:
empty_df = pd.DataFrame({})
empty_df

Empty DataFrame
Columns: []
Index: []

In [9]:
empty_df = pd.DataFrame({
    "Gene": [],
    "Control_Expression": [],
    "Treatment_Expression": [],
    "Significant": []
    })
empty_df

Empty DataFrame
Columns: [Gene, Control_Expression, Treatment_Expression, Significant]
Index: []

In [10]:
df.to_csv("bioinf_test.csv", index=False)

In [11]:
df_new = pd.read_csv("bioinf_test.csv")
df_new

    Gene  Control_Expression  Treatment_Expression Significant
0  BRCA1                10.5                  15.2         Yes
1   TP53                 8.2                   7.9          No
2   EGFR                 5.6                  12.3         Yes
3    MYC                 9.1                  14.8         Yes
4   PTEN                 7.4                   6.9          No

In [12]:
import pandas as pd

df = pd.read_csv("gene_expression.csv")  # Make sure you have this file in your current location

In [13]:
df.head()

    Gene  Control_Expression  Treatment_Expression Significant
0  Brca1                  12                    18         Yes
1   Tp53                  20                    19          No
2    Myc                  15                    25         Yes
3   Egfr                  10                    14          No
4   Akt1                  18                    30         Yes

In [14]:
df.head(10)        # Displays first 10 rows

     Gene  Control_Expression  Treatment_Expression Significant
0   Brca1                  12                    18         Yes
1    Tp53                  20                    19          No
2     Myc                  15                    25         Yes
3    Egfr                  10                    14          No
4    Akt1                  18                    30         Yes
5   Vegfa                  11                    17         Yes
6   Mapk1                  14                    16          No
7    Mtor                  13                    21         Yes
8  Pik3ca                  16                    22         Yes
9  Cdkn1a                   9                    12          No

In [15]:
df.head(2)          # Displays first 2 rows

    Gene  Control_Expression  Treatment_Expression Significant
0  Brca1                  12                    18         Yes
1   Tp53                  20                    19          No

In [16]:
df.tail()

     Gene  Control_Expression  Treatment_Expression Significant
35   Hras                  12                    16          No
36  Foxo3                  11                    18         Yes
37  Gata3                  10                    15          No
38   E2f1                  17                    23         Yes
39  Ccnd1                  20                    24          No

In [17]:
df.tail(10)       # Displays last 10 rows

     Gene  Control_Expression  Treatment_Expression Significant
30  Casp8                  10                    16         Yes
31   Mdm2                  15                    21         Yes
32  Erbb2                  18                    24         Yes
33   Kras                  14                    20         Yes
34   Nras                  13                    17          No
35   Hras                  12                    16          No
36  Foxo3                  11                    18         Yes
37  Gata3                  10                    15          No
38   E2f1                  17                    23         Yes
39  Ccnd1                  20                    24          No

In [18]:
df.tail(2)          # Displays last 2 rows

     Gene  Control_Expression  Treatment_Expression Significant
38   E2f1                  17                    23         Yes
39  Ccnd1                  20                    24          No

In [19]:
df.columns

Index(['Gene', 'Control_Expression', 'Treatment_Expression', 'Significant'], dtype='object')

In [20]:
df.index

RangeIndex(start=0, stop=40, step=1)

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Gene                  40 non-null     object
 1   Control_Expression    40 non-null     int64
 2   Treatment_Expression  40 non-null     int64
 3   Significant           40 non-null     object
dtypes: int64(2), object(2)
memory usage: 1.4+ KB

In [22]:
df.shape

(40, 4)

In [23]:
len(df)

40

In [24]:
df.ndim

2

In [25]:
df.shape[0]

40

In [26]:
df.shape[1]

4

In [27]:
df_copy = df.copy()

In [28]:
df_copy.columns

Index(['Gene', 'Control_Expression', 'Treatment_Expression', 'Significant'], dtype='object')

In [29]:
df_copy.columns = [
    'Gene',
    'Control Expression',
    'Treatment Expression',
    'Significant'
    ]

In [30]:
df_copy.index

RangeIndex(start=0, stop=40, step=1)

In [31]:
df_indexed = df_copy.set_index('Gene')

In [32]:
df_indexed.head()

       Control Expression  Treatment Expression Significant
Gene
Brca1                  12                    18         Yes
Tp53                   20                    19          No
Myc                    15                    25         Yes
Egfr                   10                    14          No
Akt1                   18                    30         Yes

In [33]:
df_indexed.shape

(40, 3)

In [34]:
df_indexed.index

Index(['Brca1', 'Tp53', 'Myc', 'Egfr', 'Akt1', 'Vegfa', 'Mapk1', 'Mtor',
       'Pik3ca', 'Cdkn1a', 'Jun', 'Fos', 'Stat3', 'Sox2', 'Nanog', 'Cdk2',
       'Cdk4', 'Rb1', 'Pten', 'Hif1a', 'Nfkb1', 'Il6', 'Tnf', 'Jak2', 'Smad4',
       'Tgfb1', 'Apaf1', 'Bax', 'Bcl2', 'Casp3', 'Casp8', 'Mdm2', 'Erbb2',
       'Kras', 'Nras', 'Hras', 'Foxo3', 'Gata3', 'E2f1', 'Ccnd1'],
      dtype='object', name='Gene')

In [35]:
df_reset = df_indexed.reset_index()

In [36]:
df_reset.head()

    Gene  Control Expression  Treatment Expression Significant
0  Brca1                  12                    18         Yes
1   Tp53                  20                    19          No
2    Myc                  15                    25         Yes
3   Egfr                  10                    14          No
4   Akt1                  18                    30         Yes

In [37]:
df_reset.shape

(40, 4)

In [38]:
df_info = pd.read_csv("gene_expression.csv")
df_info.head()

    Gene  Control_Expression  Treatment_Expression Significant
0  Brca1                  12                    18         Yes
1   Tp53                  20                    19          No
2    Myc                  15                    25         Yes
3   Egfr                  10                    14          No
4   Akt1                  18                    30         Yes

In [39]:
df_info = pd.read_csv("gene_expression.csv")
df_info.head()

    Gene  Control_Expression  Treatment_Expression Significant
0  Brca1                  12                    18         Yes
1   Tp53                  20                    19          No
2    Myc                  15                    25         Yes
3   Egfr                  10                    14          No
4   Akt1                  18                    30         Yes

In [42]:
gene_info = df_info['Gene']
print(gene_info)

0      Brca1
1       Tp53
2        Myc
3       Egfr
4       Akt1
5      Vegfa
6      Mapk1
7       Mtor
8     Pik3ca
9     Cdkn1a
10       Jun
11       Fos
12     Stat3
13      Sox2
14     Nanog
15      Cdk2
16      Cdk4
17       Rb1
18      Pten
19     Hif1a
20     Nfkb1
21       Il6
22       Tnf
23      Jak2
24     Smad4
25     Tgfb1
26     Apaf1
27       Bax
28      Bcl2
29     Casp3
30     Casp8
31      Mdm2
32     Erbb2
33      Kras
34      Nras
35      Hras
36     Foxo3
37     Gata3
38      E2f1
39     Ccnd1
Name: Gene, dtype: object

In [47]:
control_exp = df_info['Control_Expression']
print(control_exp)
print(type(control_exp))

0     12
1     20
2     15
3     10
4     18
5     11
6     14
7     13
8     16
9      9
10     8
11     7
12    13
13    10
14     6
15    15
16    14
17    19
18    17
19    12
20    11
21     9
22     8
23    14
24    13
25    12
26    10
27    11
28    16
29     9
30    10
31    15
32    18
33    14
34    13
35    12
36    11
37    10
38    17
39    20
Name: Control_Expression, dtype: int64
<class 'pandas.core.series.Series'>

In [48]:
control_exp = df_info[['Control_Expression']]
print(control_exp)
print(type(control_exp))

    Control_Expression
0                   12
1                   20
2                   15
3                   10
4                   18
5                   11
6                   14
7                   13
8                   16
9                    9
10                   8
11                   7
12                  13
13                  10
14                   6
15                  15
16                  14
17                  19
18                  17
19                  12
20                  11
21                   9
22                   8
23                  14
24                  13
25                  12
26                  10
27                  11
28                  16
29                   9
30                  10
31                  15
32                  18
33                  14
34                  13
35                  12
36                  11
37                  10
38                  17
39                  20
<class 'pandas.core.frame.DataFrame'>

In [50]:
gene_info_1 = df_info['Gene']
gene_info_2 = df_info.Gene

print(gene_info_1)
print("\n")
print(gene_info_2)

0      Brca1
1       Tp53
2        Myc
3       Egfr
4       Akt1
5      Vegfa
6      Mapk1
7       Mtor
8     Pik3ca
9     Cdkn1a
10       Jun
11       Fos
12     Stat3
13      Sox2
14     Nanog
15      Cdk2
16      Cdk4
17       Rb1
18      Pten
19     Hif1a
20     Nfkb1
21       Il6
22       Tnf
23      Jak2
24     Smad4
25     Tgfb1
26     Apaf1
27       Bax
28      Bcl2
29     Casp3
30     Casp8
31      Mdm2
32     Erbb2
33      Kras
34      Nras
35      Hras
36     Foxo3
37     Gata3
38      E2f1
39     Ccnd1
Name: Gene, dtype: object


0      Brca1
1       Tp53
2        Myc
3       Egfr
4       Akt1
5      Vegfa
6      Mapk1
7       Mtor
8     Pik3ca
9     Cdkn1a
10       Jun
11       Fos
12     Stat3
13      Sox2
14     Nanog
15      Cdk2
16      Cdk4
17       Rb1
18      Pten
19     Hif1a
20     Nfkb1
21       Il6
22       Tnf
23      Jak2
24     Smad4
25     Tgfb1
26     Apaf1
27       Bax
28      Bcl2
29     Casp3
30     Casp8
31      Mdm2
32     Erbb2
33      Kras
34      Nras
35      Hras
36     Foxo3
37     Gata3
38      E2f1
39     Ccnd1
Name: Gene, dtype: object

In [24]:
'Control Expression'
'Treatment Expression'

'Treatment Expression'

In [53]:
df_copy = pd.DataFrame({'Control Expression': [2,32,14,5], 'Treatment Expression': [10, 12, 1, 20]})

In [54]:
df_copy.Control Expression    # SyntaxError

SyntaxError: invalid syntax (1215283342.py, line 1)

In [55]:
df_copy['Control Expression']    #  Works

0     2
1    32
2    14
3     5
Name: Control Expression, dtype: int64

In [57]:
out1 = df_info[['Gene', 'Significant']]
print(out1)

      Gene Significant
0    Brca1         Yes
1     Tp53          No
2      Myc         Yes
3     Egfr          No
4     Akt1         Yes
5    Vegfa         Yes
6    Mapk1          No
7     Mtor         Yes
8   Pik3ca         Yes
9   Cdkn1a          No
10     Jun         Yes
11     Fos          No
12   Stat3         Yes
13    Sox2         Yes
14   Nanog          No
15    Cdk2          No
16    Cdk4         Yes
17     Rb1          No
18    Pten          No
19   Hif1a         Yes
20   Nfkb1         Yes
21     Il6         Yes
22     Tnf          No
23    Jak2         Yes
24   Smad4          No
25   Tgfb1         Yes
26   Apaf1          No
27     Bax         Yes
28    Bcl2          No
29   Casp3          No
30   Casp8         Yes
31    Mdm2         Yes
32   Erbb2         Yes
33    Kras         Yes
34    Nras          No
35    Hras          No
36   Foxo3         Yes
37   Gata3          No
38    E2f1         Yes
39   Ccnd1          No

In [29]:
df_iloc[row_indexer, column_indexer]

NameError: name 'df_iloc' is not defined

In [58]:
out2 = df_info.iloc[:, 1]
print(out2)

0     12
1     20
2     15
3     10
4     18
5     11
6     14
7     13
8     16
9      9
10     8
11     7
12    13
13    10
14     6
15    15
16    14
17    19
18    17
19    12
20    11
21     9
22     8
23    14
24    13
25    12
26    10
27    11
28    16
29     9
30    10
31    15
32    18
33    14
34    13
35    12
36    11
37    10
38    17
39    20
Name: Control_Expression, dtype: int64

In [59]:
out3 = df_info.iloc[:, 1:3]
print(out3)

    Control_Expression  Treatment_Expression
0                   12                    18
1                   20                    19
2                   15                    25
3                   10                    14
4                   18                    30
5                   11                    17
6                   14                    16
7                   13                    21
8                   16                    22
9                    9                    12
10                   8                    15
11                   7                    11
12                  13                    20
13                  10                    18
14                   6                    10
15                  15                    17
16                  14                    23
17                  19                    18
18                  17                    13
19                  12                    19
20                  11                    16
21                   9                    18
22                   8                    14
23                  14                    20
24                  13                    15
25                  12                    18
26                  10                    12
27                  11                    17
28                  16                    15
29                   9                    14
30                  10                    16
31                  15                    21
32                  18                    24
33                  14                    20
34                  13                    17
35                  12                    16
36                  11                    18
37                  10                    15
38                  17                    23
39                  20                    24

In [60]:
row1 = df_info.iloc[2]
print(row1)

Gene                    Myc
Control_Expression       15
Treatment_Expression     25
Significant             Yes
Name: 2, dtype: object

In [61]:
row_subset = df_info.iloc[1:4]
print(row_subset)

   Gene  Control_Expression  Treatment_Expression Significant
1  Tp53                  20                    19          No
2   Myc                  15                    25         Yes
3  Egfr                  10                    14          No

In [62]:
df_indexed = df_info.set_index('Gene')
print(df_indexed.head())

       Control_Expression  Treatment_Expression Significant
Gene
Brca1                  12                    18         Yes
Tp53                   20                    19          No
Myc                    15                    25         Yes
Egfr                   10                    14          No
Akt1                   18                    30         Yes

In [65]:
row_my_gene = df_indexed.loc['Myc']
print(row_my_gene)

Control_Expression       15
Treatment_Expression     25
Significant             Yes
Name: Myc, dtype: object

In [66]:
rows_subset = df_indexed.loc[['Tp53', 'Egfr']]
print(rows_subset)

      Control_Expression  Treatment_Expression Significant
Gene
Tp53                  20                    19          No
Egfr                  10                    14          No

In [67]:
out1 = df_info.iloc[1:4, 1:3]
print(out1)

   Control_Expression  Treatment_Expression
1                  20                    19
2                  15                    25
3                  10                    14

In [94]:
df_info = pd.read_csv("gene_expression.csv")
df_info_subset1 = df_info[df_info['Significant'] == 'Yes']
print(df_info_subset1.head())

    Gene  Control_Expression  Treatment_Expression Significant
0  Brca1                  12                    18         Yes
2    Myc                  15                    25         Yes
4   Akt1                  18                    30         Yes
5  Vegfa                  11                    17         Yes
7   Mtor                  13                    21         Yes

In [95]:
df_info_subset2 = df_info[~(df_info['Significant'] == 'No')]
print(df_info_subset2.head())

    Gene  Control_Expression  Treatment_Expression Significant
0  Brca1                  12                    18         Yes
2    Myc                  15                    25         Yes
4   Akt1                  18                    30         Yes
5  Vegfa                  11                    17         Yes
7   Mtor                  13                    21         Yes

In [96]:
df_info_subset3 = df_info[(df_info['Significant'] == 'Yes') & (df_info['Treatment_Expression'] > 100)]
print(df_info_subset3.head())

Empty DataFrame
Columns: [Gene, Control_Expression, Treatment_Expression, Significant]
Index: []

In [97]:
df_info_subset4 = df_info[(df_info['Significant'] == 'Yes') | (df_info['Treatment_Expression'] > 100)]
print(df_info_subset4.head())

    Gene  Control_Expression  Treatment_Expression Significant
0  Brca1                  12                    18         Yes
2    Myc                  15                    25         Yes
4   Akt1                  18                    30         Yes
5  Vegfa                  11                    17         Yes
7   Mtor                  13                    21         Yes

In [98]:
list_genes = ['Brca1', 'EGFR', 'KRAS']
df_info_subset5 = df_info[df_info['Gene'].isin(list_genes)]
print(df_info_subset5)

    Gene  Control_Expression  Treatment_Expression Significant
0  Brca1                  12                    18         Yes

In [99]:
import pandas as pd

# Example: match genes starting with "BR" or "EG"
df_info_subset6 = df_info[
    df_info['Gene'].str.contains(r'^(?:BR|EG)', regex=True) &
     (df_info['Significant'] == 'Yes')
]
df_info_subset6

Empty DataFrame
Columns: [Gene, Control_Expression, Treatment_Expression, Significant]
Index: []

In [100]:
df_info_subset7 = df_info[
        df_info['Gene'].str.contains(r'\d$', regex=True) &
        (df_info['Significant'] == 'Yes')
]
df_info_subset7

     Gene  Control_Expression  Treatment_Expression Significant
0   Brca1                  12                    18         Yes
4    Akt1                  18                    30         Yes
12  Stat3                  13                    20         Yes
13   Sox2                  10                    18         Yes
16   Cdk4                  14                    23         Yes
20  Nfkb1                  11                    16         Yes
21    Il6                   9                    18         Yes
23   Jak2                  14                    20         Yes
25  Tgfb1                  12                    18         Yes
30  Casp8                  10                    16         Yes
31   Mdm2                  15                    21         Yes
32  Erbb2                  18                    24         Yes
36  Foxo3                  11                    18         Yes
38   E2f1                  17                    23         Yes

In [101]:
# Update ‘Significant’ column using conditional statements
df_info.loc[df_info['Significant'] == 'Yes', 'Significant'] = 'Positive'
df_info.loc[df_info['Significant'] == 'No', 'Significant'] = 'Negative'

# Check the first few rows
print(df_info.head())

    Gene  Control_Expression  Treatment_Expression Significant
0  Brca1                  12                    18    Positive
1   Tp53                  20                    19    Negative
2    Myc                  15                    25    Positive
3   Egfr                  10                    14    Negative
4   Akt1                  18                    30    Positive

In [102]:
# Create a new column based on existing conditions
df_info.loc[df_info['Significant'] == 'Positive', 'Significant_two'] = 'Yes'
df_info.loc[df_info['Significant'] == 'Negative', 'Significant_two'] = 'No'

# Check the first few rows
print(df_info.head())

    Gene  Control_Expression  Treatment_Expression Significant Significant_two
0  Brca1                  12                    18    Positive             Yes
1   Tp53                  20                    19    Negative              No
2    Myc                  15                    25    Positive             Yes
3   Egfr                  10                    14    Negative              No
4   Akt1                  18                    30    Positive             Yes

In [103]:
# Check the number of rows in the DataFrame
len(df_info)    # Output: 40

40

In [104]:
# Create a list for the new column
experiment_day = ["Monday"]*10 + ["Tuesday"]*10 + ["Wednesday"]*10 + ["Thursday"]*5 + ["Friday"]*5

# Verify the length
len(experiment_day)  # Output: 40

40

In [105]:
# Add a new column to the DataFrame
df_info.loc[:, 'Day_of_experiment'] = experiment_day

# Check the first few rows
print(df_info.head())

    Gene  Control_Expression  Treatment_Expression Significant  \
0  Brca1                  12                    18    Positive
1   Tp53                  20                    19    Negative
2    Myc                  15                    25    Positive
3   Egfr                  10                    14    Negative
4   Akt1                  18                    30    Positive

  Significant_two Day_of_experiment
0             Yes            Monday
1              No            Monday
2             Yes            Monday
3              No            Monday
4             Yes            Monday

In [106]:
# Check a new row
new_entry = ["C9orf72", 50, 99, "Positive", "Yes", "Friday"]

In [107]:
# Add a new row to the DataFrame
df_info.loc[len(df_info)] = new_entry

# Check the last few rows
print(df_info.tail())

       Gene  Control_Expression  Treatment_Expression Significant  \
36    Foxo3                  11                    18    Positive
37    Gata3                  10                    15    Negative
38     E2f1                  17                    23    Positive
39    Ccnd1                  20                    24    Negative
40  C9orf72                  50                    99    Positive

   Significant_two Day_of_experiment
36             Yes            Friday
37              No            Friday
38             Yes            Friday
39              No            Friday
40             Yes            Friday

In [108]:
# Delete a single column
df_info = df_info.drop('Day_of_experiment', axis=1)

# Check the updated DataFrame
print(df_info.head())

    Gene  Control_Expression  Treatment_Expression Significant Significant_two
0  Brca1                  12                    18    Positive             Yes
1   Tp53                  20                    19    Negative              No
2    Myc                  15                    25    Positive             Yes
3   Egfr                  10                    14    Negative              No
4   Akt1                  18                    30    Positive             Yes

In [109]:
experiment_day = ["Monday"]*10 + ["Tuesday"]*10 + ["Wednesday"]*10 + ["Thursday"]*5 + ["Friday"]*6
df_info.loc[:, 'Day_of_experiment'] = experiment_day

# Delete a single column
df_info = df_info.drop(['Day_of_experiment', 'Significant'], axis=1)

# Check the updated DataFrame
print(df_info.head())

    Gene  Control_Expression  Treatment_Expression Significant_two
0  Brca1                  12                    18             Yes
1   Tp53                  20                    19              No
2    Myc                  15                    25             Yes
3   Egfr                  10                    14              No
4   Akt1                  18                    30             Yes

In [110]:
# Delete a single row (e.g., index 3)
df_info = df_info.drop(3, axis=0)

# Check the updated DataFrame
print(df_info.head())

    Gene  Control_Expression  Treatment_Expression Significant_two
0  Brca1                  12                    18             Yes
1   Tp53                  20                    19              No
2    Myc                  15                    25             Yes
4   Akt1                  18                    30             Yes
5  Vegfa                  11                    17             Yes

In [111]:
# Delete multiple rows (e.g., indices 2 and 4)
df_info = df_info.drop([2, 4], axis=0)

# Verify
print(df_info.head())

    Gene  Control_Expression  Treatment_Expression Significant_two
0  Brca1                  12                    18             Yes
1   Tp53                  20                    19              No
5  Vegfa                  11                    17             Yes
6  Mapk1                  14                    16              No
7   Mtor                  13                    21             Yes

In [112]:
import pandas as pd

data = {
    'Gene': ['BRCA1', 'TP53', 'MYC', 'EGFR', None, None, 'NFKBIZ'],
    'Control Expression': [50, None, 80, 100, 200, None, 70],
    'Treatment Expression': [70, 140, None, 150, 180, None, 200],
    'Significant': ['Yes', 'Yes', 'No', 'Yes', None, None, 'Yes'],
    'Experiment Day': [None, None, None, None, None, None, 'Friday'],
    'Experiment replicated': ['Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes']
}

df_new = pd.DataFrame(data)
df_new

,Gene,Control Expression,Treatment Expression,Significant,Experiment Day,Experiment replicated
0,BRCA1,50.0,70.0,Yes,None,Yes
1,TP53,NaN,140.0,Yes,None,Yes
2,MYC,80.0,NaN,No,None,Yes
3,EGFR,100.0,150.0,Yes,None,Yes
4,None,200.0,180.0,None,None,Yes
5,None,NaN,NaN,None,None,Yes
6,NFKBIZ,70.0,200.0,Yes,Friday,Yes

In [113]:
df_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Gene                   5 non-null      object
 1   Control Expression     5 non-null      float64
 2   Treatment Expression   5 non-null      float64
 3   Significant            5 non-null      object
 4   Experiment Day         1 non-null      object
 5   Experiment replicated  7 non-null      object
dtypes: float64(2), object(4)
memory usage: 468.0+ bytes

In [114]:
df_new.isna()

,Gene,Control Expression,Treatment Expression,Significant,Experiment Day,Experiment replicated
0,False,False,False,False,True,False
1,False,True,False,False,True,False
2,False,False,True,False,True,False
3,False,False,False,False,True,False
4,True,False,False,True,True,False
5,True,True,True,True,True,False
6,False,False,False,False,False,False

In [115]:
df_new.isna().any(axis=0)

Gene                      True
Control Expression        True
Treatment Expression      True
Significant               True
Experiment Day            True
Experiment replicated    False
dtype: bool

In [116]:
df_new.isna().all(axis=0)

Gene                     False
Control Expression       False
Treatment Expression     False
Significant              False
Experiment Day           False
Experiment replicated    False
dtype: bool

In [119]:
df_new.isna().any(axis=1)

0     True
1     True
2     True
3     True
4     True
5     True
6    False
dtype: bool

In [120]:
df_new.isna().all(axis=1)

0    False
1    False
2    False
3    False
4    False
5    False
6    False
dtype: bool

In [121]:
df_new_copy = df_new.copy()

In [122]:
# dropping columns where all its value are None
df_new_copy_1 = df_new_copy.dropna(axis=1, how='all')
df_new_copy_1

,Gene,Control Expression,Treatment Expression,Significant,Experiment Day,Experiment replicated
0,BRCA1,50.0,70.0,Yes,None,Yes
1,TP53,NaN,140.0,Yes,None,Yes
2,MYC,80.0,NaN,No,None,Yes
3,EGFR,100.0,150.0,Yes,None,Yes
4,None,200.0,180.0,None,None,Yes
5,None,NaN,NaN,None,None,Yes
6,NFKBIZ,70.0,200.0,Yes,Friday,Yes

In [123]:
# droping columns where atleast one value is None
df_new_copy_2 = df_new_copy.dropna(axis=1, how='any')
df_new_copy_2

  Experiment replicated
0                   Yes
1                   Yes
2                   Yes
3                   Yes
4                   Yes
5                   Yes
6                   Yes

In [124]:
# droping rows where all its value are None
df_new_copy_3 = df_new_copy.dropna(axis=0, how='all')
df_new_copy_3

,Gene,Control Expression,Treatment Expression,Significant,Experiment Day,Experiment replicated
0,BRCA1,50.0,70.0,Yes,None,Yes
1,TP53,NaN,140.0,Yes,None,Yes
2,MYC,80.0,NaN,No,None,Yes
3,EGFR,100.0,150.0,Yes,None,Yes
4,None,200.0,180.0,None,None,Yes
5,None,NaN,NaN,None,None,Yes
6,NFKBIZ,70.0,200.0,Yes,Friday,Yes

In [125]:
# droping rows where atleast one value is None
df_new_copy_4 = df_new_copy.dropna(axis=0, how='any')
df_new_copy_4

,Gene,Control Expression,Treatment Expression,Significant,Experiment Day,Experiment replicated
6,NFKBIZ,70.0,200.0,Yes,Friday,Yes

In [126]:
# fillna: impute missing values in column
df_new_copy['Control Expression'] = df_new_copy['Control Expression'].fillna(0)
df_new_copy

,Gene,Control Expression,Treatment Expression,Significant,Experiment Day,Experiment replicated
0,BRCA1,50.0,70.0,Yes,None,Yes
1,TP53,0.0,140.0,Yes,None,Yes
2,MYC,80.0,NaN,No,None,Yes
3,EGFR,100.0,150.0,Yes,None,Yes
4,None,200.0,180.0,None,None,Yes
5,None,0.0,NaN,None,None,Yes
6,NFKBIZ,70.0,200.0,Yes,Friday,Yes

In [127]:
df_new_copy.loc[5, :] = df_new_copy.loc[5, :].fillna(0)
df_new_copy

,Gene,Control Expression,Treatment Expression,Significant,Experiment Day,Experiment replicated
0,BRCA1,50.0,70.0,Yes,None,Yes
1,TP53,0.0,140.0,Yes,None,Yes
2,MYC,80.0,NaN,No,None,Yes
3,EGFR,100.0,150.0,Yes,None,Yes
4,None,200.0,180.0,None,None,Yes
5,0,0.0,0.0,0,0,Yes
6,NFKBIZ,70.0,200.0,Yes,Friday,Yes

In [128]:
import pandas as pd
# Gene expression DataFrames
df1 = pd.DataFrame({
    "Gene": ["BRCA1", "TP53", "MYC"],
    "Control_Expression": [50, 120, 80],
    "Treatment_Expression": [70, 140, 60]
})

df2 = pd.DataFrame({
    "Gene": ["EGFR", "KRAS"],
    "Control_Expression": [100, 200],
    "Treatment_Expression": [150, 180]
})
print("DataFrame 1:")
print(df1)
print("\nDataFrame 2:")
print(df2)

DataFrame 1:
    Gene  Control_Expression  Treatment_Expression
0  BRCA1                  50                    70
1   TP53                 120                   140
2    MYC                  80                    60

DataFrame 2:
   Gene  Control_Expression  Treatment_Expression
0  EGFR                 100                   150
1  KRAS                 200                   180

In [129]:
df = pd.concat([df1, df2], axis=0).reset_index().drop('index', axis=1)
df

    Gene  Control_Expression  Treatment_Expression
0  BRCA1                  50                    70
1   TP53                 120                   140
2    MYC                  80                    60
3   EGFR                 100                   150
4   KRAS                 200                   180

In [130]:
# Concat vertically
# Gene metadata DataFrame
metadata = pd.DataFrame({
    "Chromosome": ["17", "17", "8", "7", "12"],
    "Function": ["DNA Repair", "Tumor Suppressor", "Transcription Factor", "Cell Growth", "Cell Growth"]
})
metadata

  Chromosome              Function
0         17            DNA Repair
1         17      Tumor Suppressor
2          8  Transcription Factor
3          7           Cell Growth
4         12           Cell Growth

In [131]:
# Horizontal concatenation
combined_horizontal = pd.concat([df, metadata], axis=1)
combined_horizontal

,Gene,Control_Expression,Treatment_Expression,Chromosome,Function
0,BRCA1,50,70,17,DNA Repair
1,TP53,120,140,17,Tumor Suppressor
2,MYC,80,60,8,Transcription Factor
3,EGFR,100,150,7,Cell Growth
4,KRAS,200,180,12,Cell Growth

In [132]:
df4 = pd.DataFrame(
    {
        'Gene': ['BRCA1', 'TP53', 'MYC', 'EGFR', 'KRAS'],
        'Expression': [50, 120, 80, 100, 200]
    }
)

df5 = pd.DataFrame(
    {
        'Gene': ['BRCA1', 'EGFR'],
        'Chromosome': [17, 7]
    }
)

In [133]:
pd.merge(df4, df5, on="Gene", how="join_type")

UnboundLocalError: cannot access local variable 'lidx' where it is not associated with a value

In [134]:
df_complete_inner = pd.merge(df4, df5, on="Gene", how="inner")
df_complete_inner

    Gene  Expression  Chromosome
0  BRCA1          50          17
1   EGFR         100           7

In [135]:
df_complete_outer = pd.merge(df4, df5, on="Gene", how="outer")
df_complete_outer

    Gene  Expression  Chromosome
0  BRCA1          50        17.0
1   EGFR         100         7.0
2   KRAS         200         NaN
3    MYC          80         NaN
4   TP53         120         NaN

In [136]:
df_complete_left = pd.merge(df4, df5, on="Gene", how="left")
df_complete_left

    Gene  Expression  Chromosome
0  BRCA1          50        17.0
1   TP53         120         NaN
2    MYC          80         NaN
3   EGFR         100         7.0
4   KRAS         200         NaN

In [137]:
df_complete_right = pd.merge(df4, df5, on="Gene", how="right")
df_complete_right

    Gene  Expression  Chromosome
0  BRCA1          50          17
1   EGFR         100           7